### ISSUE TITLE
Bug in the pong game

### ISSUE THREAD

**Issue by aminya** [battlelinegames/VectorEngine#1]
The ball somehow went to the left and it doesn't come out anymore.
![bug](https://user-images.githubusercontent.com/16418197/116783135-ad82c200-aa52-11eb-8547-b41a3e01c542.gif)

**Comment by battlelinegames** [comment]
To me, it looks like the ball is rendering just off-screen.  I'm guessing you clicked a few times to speed the ball up.  The ball is probably going straight up and down because the code only reflects the x-direction when the ball goes off-screen.

**Comment by aminya** [comment]
Yeah, if you can detect this situation and reset the game, it would be good.

**Comment by battlelinegames** [comment]
Does it happen often?

**Comment by battlelinegames** [comment]
You know, it might happen when the speed is enough that the ball leaves the screen and bounces back and forth offscreen.

**Comment by JairusSW** [comment]
Yeah... I get the same problem... You can get to it (every time) of you put your paddle in the bottom-left at the start of the game and leave it. It'll bounce around and after 1min, the bug will switch on.

**Comment by battlelinegames** [comment]
I think I fixed this a while ago and forgot to close this.  If it is still a problem, please let me know.
